project:
  type: book
  output-dir: docs

book:
  title: "P01：金融数据获取、管理与初步分析"
  author: "杨艺欣（25210279）"
  chapters:
    - index.qmd
    - 01_download.ipynb
    - 02_clean.ipynb
    - 03_analysis.ipynb

format:
  html:
    theme: cosmo
    toc: true
    code-fold: show

execute:
  freeze: auto
